export const GET_SEARCH_WORD = "GET_SEARCH_WORD";
export const GET_SEARCH_OFFERS = "GET_SEARCH_OFFERS";
export const GET_SEARCH_OPTIONS = "GET_SEARCH_OPTIONS";
export const GET_SPEECH_CODES = "GET_SPEECH_CODES";
export const GET_PARENT_COORDS = "GET_PARENT_COORDS";